//#@ import namespace="Newtonsoft.Json" #

// @ import namespace="Microsoft.AspNetCore.Mvc.ApiExplorer"
//nuget package dll hell resolverhow to import @ import namespace="Microsoft.NETCore.Targets" #
// #@ import namespace="Microsoft.AspNetCore.Mvc" #
// #@ import namespace="System.Runtime" #



//AUTOGENERATED DO NOT EDIT THIS FILE 23.11.2020 15:09:36
////////////////////
// available hubs //
////////////////////
//#region available hubs
//JS header:


declare var $:any;
import fetchival from 'fetchival';

export class Api {
    constructor(baseurl: string) {
        this.url = baseurl;
  
    }
    url:string;

}
//#endregion available hubs


export default Api;
//#endregion data contracts

